# Numpy

NumPy is a fundamental library for scientific computing is python . It provides support for arrays and matrices, along with a collection of mathematical function to operate on these data structure . In this lesson , we will cover the basics of Numpy, focusing on arrays and vectorized operations.

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

#create array using numpy
#create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
#1D array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [5]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [6]:
#2D array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
np.ones((2,4)) # deep learning used this function 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
#Identity matrix

np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Attributes of numpy
arr=np.array([[1,2,3],[4,5,6]])

print('Array:\n',arr)
print('Shape:',arr.shape)
print('Number of dimension:',arr.ndim)
print('Size(number of elements):',arr.size)
print('Data type:',arr.dtype)
print('Item size(in bytes):',arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimension: 2
Size(number of elements): 6
Data type: int64
Item size(in bytes): 8


In [11]:
#Numpy Vectorized operation

arr1=np.array([12,4,6,7,8])
arr2=np.array([13,87,9,66,5])

#Elements wise addition
print('Addition:',arr1+arr2)

#Elements wise substraction
print('Substraction:',arr1-arr2)

#Elements wise Multiplication
print('Multiplication:',arr1*arr2)

#Elements wise Division
print('Division:',arr1/arr2)

Addition: [25 91 15 73 13]
Substraction: [ -1 -83  -3 -59   3]
Multiplication: [156 348  54 462  40]
Division: [0.92307692 0.04597701 0.66666667 0.10606061 1.6       ]


In [12]:
#Universal Function

arr=np.array([2,3,5,6,8])

#Square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

#Sine
print(np.sin(arr))

#Natural log
print(np.log)

[1.41421356 1.73205081 2.23606798 2.44948974 2.82842712]
[   7.3890561    20.08553692  148.4131591   403.42879349 2980.95798704]
[ 0.90929743  0.14112001 -0.95892427 -0.2794155   0.98935825]
<ufunc 'log'>


In [13]:
#Array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
print(arr[0][0])
print(arr[0][2])
print(arr[0:2,2:])
print(arr[1:,2:])
print(arr[0:1,2:])

1
3
[[3 4]
 [7 8]]
[[ 7  8]
 [11 12]]
[[3 4]]


In [22]:
#Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [23]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


# Statistical concept- Normalization
To have a mean of 0 and standard deviation of 1


In [24]:
data=np.array([1,2,3,4,5])
#Calculate the mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

#Normalization the data
normalized_data=(data-mean)/std_dev
print("Normalized data:",normalized_data)


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [25]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean=np.mean(data)
print("mean:",mean)

#median
median=np.median(data)
print('median:',median)

#standard deviation
std_dev=np.std(data)
print("standard deviation:",std_dev)

#variance
variance=np.var(data)
print("variance:",variance)

mean: 5.5
median: 5.5
standard deviation: 2.8722813232690143
variance: 8.25


In [31]:
#Logical operation
data=np.array([1,2,8,4,5,3,8,9,10])

data>3
data[(data>=5) & (data<=8)]

array([8, 5, 8])